version: 2
jobs:
  build:
    working_directory: ~/scala-forklift
    docker:
      - image: cimg/openjdk:11.0.25
      - image: cimg/mysql:8.0
        environment:
          MYSQL_DATABASE: circle_test
          MYSQL_ALLOW_EMPTY_PASSWORD: true
      - image: cimg/postgres:9.6.23
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
    environment:
      SBT_VERSION: 1.10.3
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Install python dependencies
          command: |
                    apt update && apt install -y curl
                    sudo apt-get update
                    sudo apt-get install -y python3-pip git
                    pip3 install awscli
                    sudo apt-get clean && sudo apt-get autoclean
      - run:
          name: Setup sbt
          command: |
                    cd ..
                    curl -L -o sbt-$SBT_VERSION.tgz https://github.com/sbt/sbt/releases/download/v$SBT_VERSION/sbt-$SBT_VERSION.tgz
                    tar -xvf sbt-$SBT_VERSION.tgz
                    cd sbt/bin
                    sudo chmod +x sbt
                    export PATH=$PATH:$(pwd)
                    cd ~/scala-forklift
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          name: Crosscompile scala-forklift
          command: sbt +compile
      - run:
          name: Compile tests
          command: |
            sbt +test:compile
            sbt +publishLocal
      - run:
          name: Test scala-forklift scala 2.13
          command: sbt '++ 2.13.1; test:test'
          environment:
            JAVA_OPTS: "-Xms256m -Xmx512m"
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
