version: 2
jobs:
  build:
    working_directory: ~/scala-forklift
    docker:
      - image: circleci/openjdk:8
      - image: circleci/mysql:5.7.29
        environment:
          MYSQL_DATABASE: circle_test
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
      - image: circleci/postgres:9.6.9
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
    environment:
      SBT_VERSION: 1.10.3
    steps:
      - run: echo 'export ARTIFACT_BUILD=$CIRCLE_PROJECT_REPONAME-$CIRCLE_BUILD_NUM.zip' >> $BASH_ENV
      - run:
          name: Get sbt binary
          command: |
                    apt update && apt install -y curl
                    curl -L -o sbt-$SBT_VERSION.deb https://dl.bintray.com/sbt/debian/sbt-$SBT_VERSION.deb
                    sudo dpkg -i sbt-$SBT_VERSION.deb
                    rm sbt-$SBT_VERSION.deb
                    sudo apt-get update
                    sudo apt-get install -y sbt python-pip git
                    pip install awscli
                    sudo apt-get clean && sudo apt-get autoclean
      - checkout
      - restore_cache:
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: sbt-cache
      - run:
          name: Crossompile scala-forklift
          command: sbt +compile
      - run:
          name: Compile tests
          command: |
            sbt +test:compile
            sbt +publishLocal
      - run:
          name: Test scala-forklift scala 2.12
          command: sbt '++ 2.12.11; test:test'
          environment:
            JAVA_OPTS: "-Xms256m -Xmx512m"
      - run:
          name: Test scala-forklift scala 2.13
          command: sbt '++ 2.13.1; test:test'
          environment:
            JAVA_OPTS: "-Xms256m -Xmx512m"
      - save_cache:
          key: sbt-cache
          paths:
            - "~/.ivy2/cache"
            - "~/.sbt"
            - "~/.m2"
